imap jj <Esc>
noremap Y y$

set splitbelow
set splitright
set ignorecase
set smartcase
set wildignorecase
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set noshowmode
set hidden
set wildmenu
set wildmode=longest:full,full
set showcmd
set incsearch
set number
set relativenumber
set tildeop
set signcolumn=yes
set mouse=n
if !empty($TMUX)
    set ttymouse=xterm2
else
    set ttymouse=sgr
endif

call plug#begin('~/.vim/plugged')
Plug 'jiangmiao/auto-pairs'     " nvim-autopair.lua
Plug 'itchyny/lightline.vim'    " lualine.nvim.lua
Plug 'tpope/vim-commentary'     " nvim builtin
Plug 'tpope/vim-unimpaired'     " nvim builtin
Plug 'tpope/vim-repeat'         " nvim builtin
Plug 'tpope/vim-surround'       " nvim-surround.lua
Plug 'kana/vim-textobj-user'    " nvim-various-textobjs.lua
Plug 'kana/vim-textobj-entire'  " nvim-various-textobjs.lua
Plug 'kana/vim-textobj-indent'  " nvim-various-textobjs.lua
Plug 'pocke/vim-textobj-markdown' " nvim-various-textobjs.lua
Plug 'cposture/vim-textobj-argument' " CAN NOT BE REPLACED!
Plug 'easymotion/vim-easymotion' " hop.nvim.lua
call plug#end()

let g:lightline = { 'colorscheme': 'one', }
set laststatus=2
set background=dark

autocmd BufWinLeave ?* mkview
autocmd BufWinEnter ?* silent loadview
autocmd BufWritePre ?* %s/\v\n+%$//ge
