source ~/.bash_profile
source /etc/profile

HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=5000

eval "$(starship init zsh)"

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.sudo.zsh

export LESS="--mouse --wheel-lines=3 -R"

alias vi=vim
alias ll="ls -hls --color=auto"
alias ls="ls --color=auto"
alias la="ls -hlsA --color=auto"
alias l="ls --color=auto"

set zle_bracketed_paste
autoload -Uz bracketed-paste-magic url-quote-magic
zle -N bracketed-paste bracketed-paste-magic
zle -N self-insert url-quote-magic

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
autoload -Uz compinit
compinit

[ -f /etc/audit-env ] && source /etc/audit-env
[ -f /data/custom.sh ] && source /data/custom.sh
